### ISSUE TITLE
What is the point of this mod? F3 + H gives you the same information.

### ISSUE THREAD

**Issue by winnetrie83** [mezz/ModNameTooltip#15]
I don't intend to be rude, but i try to understand the difference between your mod and the F3 + H function?
I always use F3 + H to see modname, recipe name, itemdamage etc etc

**Comment by mezz** [comment]
This feature is built into NEI.
When I created JEI I made this feature as its own mod so that people were not forced to use it if they didn't want to.
Most people seem to use it, I think it is a little more immersive than using F3+H if you care about that.

**Comment by Insane96** [comment]
F3+H is a debug feature and also it doesn't really show up pretty, I definitely like this way better.
