### ISSUE TITLE
not available on the app

### ISSUE THREAD

**Issue by Looodon** [mezz/ModNameTooltip#25]
Hey, the mod is available on the web version of curseforge, but not the app for some reason so I can't add it to my mod list through the app. Will the game version categorization (on the website) be updated from 1.19.1 to 1.19.2 any time soon? idk if that might fix it. Thanks!

**Comment by mezz** [comment]
This mod has been updated to show up for 1.19.1 and 1.19.2 now, thanks for reporting.
