### ISSUE TITLE
Tooltip Compatibility w/ Other Mods

### ISSUE THREAD

**Issue by SnowShock35** [mezz/ModNameTooltip#3]
### Important Information

- Minecraft 1.11.2 (Tested w/ 1.11.2 but could occur on other versions)
- Minecraft Forge 13.20.0.2228
- ModNameTooltip 1.7.0

### Issue Description

Tl;Dr: Not Subscribing Tooltip w/ Lower Priority allowing other mods the ability to add tool tips that display subsequent to ModNameTooltip. 

### Issue Media

![Issue Screenshot (Tooltip being loaded in post initialisation](https://ss.blamesnow.co.uk/2017/04/1492460645-bf4b255e.png)

**Comment by mezz** [comment]
Thanks!
Fixed in 1.7.1
