### ISSUE TITLE
[1.13.3] Crash on load.

### ISSUE THREAD

**Issue by ProsperCraft** [mezz/ModNameTooltip#7]
https://gist.github.com/ProsperCraft/53885e3e1db803504ee0350050bce83b

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by ProsperCraft** [comment]
Well I had six crashes in a row trying to load a mash together and make them crash pack, but this is the most recent log with modnametooltip in it.

https://gist.github.com/ProsperCraft/09f147ceb340436b6556e266a0f6c59d

Of note, when I just ran it with modnametooltip enabled it did not crash, I was actually able to get to the main menu, and get it to crash on another mod on creating a world.

**Comment by mezz** [comment]
Thanks!

`[Client thread/FATAL] [net.minecraftforge.fml.ModLoader/]: Failed to complete lifecycle event CONSTRUCT, 2 errors found`

It looks like the Forge Mod Loader is encountering fatal errors but continues to load the game.
This puts things into a bad state. ModNameTooltip doesn't get its config loaded by Forge and then crashes when it tries to access a config value.
